(function(root){
'use strict';
const lessons=[
 {title:'Count the atoms',short:'Count atoms',intro:'Balancing changes how much of each substance reacts. Every kind of atom must have the same total on both sides.',kind:'count'},
 {title:'Balance your first equation',short:'First equation',intro:'Follow the water example one change at a time. Each coefficient multiplies every atom in its formula.',kind:'worked',left:['H2','O2'],right:['H2O'],steps:[
  {values:[1,1,1],title:'Count before changing anything',text:'Hydrogen already matches: 2 atoms on each side. Oxygen does not: O₂ has 2 O atoms, but H₂O has only 1. Start with oxygen.',focus:['O']},
  {values:[1,1,2],title:'Put a 2 in front of H₂O',text:'Two water molecules contain 2 O atoms, so oxygen now matches. That same coefficient also doubles the hydrogen: the products now contain 4 H atoms. It is normal for one change to affect another element.',focus:['H','O']},
  {values:[2,1,2],title:'Put a 2 in front of H₂, then verify',text:'Two H₂ molecules supply 4 H atoms. Both sides now have 4 H and 2 O. The coefficients 2, 1, 2 have no common factor greater than 1, so this is the smallest whole-number ratio.',focus:['H','O']}
 ],takeaway:'Recount every element after a change. A coefficient cannot change only the oxygen inside a water molecule.'},
 {title:'When the counts are 2 and 3',short:'Odd & even',intro:'Look for a common total when an element appears in different-sized groups. Oxygen is a good starting point in this example.',kind:'worked',left:['Fe','O2'],right:['Fe2O3'],steps:[
  {values:[1,1,1],title:'Find a common oxygen total',text:'O₂ brings oxygen in groups of 2; Fe₂O₃ contains groups of 3. The smallest total that both can reach is 6: 3 × 2 = 2 × 3.',focus:['O']},
  {values:[1,3,2],title:'Use 3 O₂ and 2 Fe₂O₃',text:'Oxygen is now 6 on each side. But 2 Fe₂O₃ also contains 2 × 2 = 4 Fe atoms. Count the entire formula, not just the element you are balancing.',focus:['O','Fe']},
  {values:[4,3,2],title:'Match the 4 iron atoms',text:'Put 4 in front of Fe. Both sides now contain 4 Fe and 6 O. The ratio 4 : 3 : 2 is simplest; you cannot divide all three coefficients by the same whole number greater than 1.',focus:['Fe','O']}
 ],takeaway:'Some coefficients can share a factor without the whole equation being reducible. You must be able to divide every coefficient by the same factor.'},
 {title:'Keep an unchanged group together',short:'Polyatomic groups',intro:'A polyatomic ion can be a useful counting unit when the same group stays intact on both sides of the equation.',kind:'worked',left:['Na3PO4','CaCl2'],right:['Ca3(PO4)2','NaCl'],steps:[
  {values:[1,1,1,1],title:'Spot the phosphate group',text:'PO₄ is unchanged on both sides. Na₃PO₄ contains 1 phosphate group; Ca₃(PO₄)₂ contains 2. Parentheses make the outside subscript apply to the entire group: 2 P atoms and 8 O atoms.',focus:['P','O']},
  {values:[2,1,1,1],title:'Put 2 in front of Na₃PO₄',text:'There are now 2 phosphate groups on each side, so P and O match together. The reactants also contain 2 × 3 = 6 Na atoms.',focus:['P','O','Na']},
  {values:[2,3,1,1],title:'Match calcium with 3 CaCl₂',text:'Ca₃(PO₄)₂ contains 3 Ca atoms. Three CaCl₂ units supply those 3 Ca, together with 3 × 2 = 6 Cl atoms.',focus:['Ca','Cl']},
  {values:[2,3,1,6],title:'Finish with 6 NaCl',text:'Six NaCl units supply 6 Na and 6 Cl on the product side. Verify every element in the inventory. The final ratio is 2 : 3 : 1 : 6.',focus:['Na','Cl']}
 ],takeaway:'Use this shortcut only when the group is unchanged on both sides. If the group breaks apart or changes, count its elements separately.'},
 {title:'Balance a combustion reaction',short:'Combustion',intro:'For complete combustion of a hydrocarbon to CO₂ and H₂O, balance carbon first, hydrogen second, and oxygen last.',kind:'worked',left:['C3H8','O2'],right:['CO2','H2O'],steps:[
  {values:[1,1,1,1],title:'Start with one propane molecule',text:'C₃H₈ contains 3 C atoms and 8 H atoms. Keep its coefficient at 1 while you balance carbon and hydrogen. Oxygen appears in both products, so leave O₂ until last.',focus:['C','H']},
  {values:[1,1,3,1],title:'Balance carbon with 3 CO₂',text:'Each CO₂ contains 1 C atom. Three CO₂ molecules account for the 3 C atoms in propane. They also contain 6 O atoms; keep those in mind for the final step.',focus:['C']},
  {values:[1,1,3,4],title:'Balance hydrogen with 4 H₂O',text:'Each H₂O contains 2 H atoms. Four H₂O molecules account for all 8 H atoms. The products now contain 6 O in CO₂ plus 4 O in H₂O: 10 O atoms altogether.',focus:['H','O']},
  {values:[1,5,3,4],title:'Supply 10 oxygen atoms with 5 O₂',text:'Each O₂ molecule contains 2 O atoms, so 10 ÷ 2 = 5 O₂. Verify the final totals: 3 C, 8 H, and 10 O on each side. The smallest ratio is 1 : 5 : 3 : 4.',focus:['C','H','O']}
 ],takeaway:'“Oxygen last” is a useful strategy for this pattern, not a rule for every equation. In the water example, oxygen was the useful place to start.'},
 {title:'Your turn, one decision at a time',short:'Your turn',intro:'Use the same process to make ammonia. Choose a coefficient, read the explanation, and then take the next step. This lesson has no points or penalties.',kind:'guided',left:['N2','H2'],right:['NH3']}
];
const guided=[
 {values:[1,1,1],prompt:'What coefficient belongs in front of NH₃ to balance nitrogen?',choices:['1','2','3'],answer:1,explanation:'N₂ contains 2 N atoms. Each NH₃ contains 1, so use 2 NH₃. This also gives the products 6 H atoms.',wrong:['One NH₃ contains only 1 N atom. N₂ supplies 2 N atoms; you need two copies of NH₃.','','The 3 in NH₃ counts hydrogen atoms, not nitrogen. Each NH₃ contains just 1 N atom.']},
 {values:[1,1,2],prompt:'There are now 6 H atoms in the products. What coefficient belongs in front of H₂?',choices:['2','3','6'],answer:1,explanation:'Each H₂ supplies 2 H atoms. Three H₂ molecules supply 3 × 2 = 6 H atoms. Nitrogen still matches.',wrong:['Two H₂ molecules supply only 4 H atoms. Divide the required 6 H atoms by 2 atoms per molecule.','','A coefficient counts molecules here, not individual atoms. Six H₂ molecules would supply 12 H atoms.']},
 {values:[2,6,4],prompt:'These larger coefficients also balance the atoms. What should you do to get the smallest whole-number ratio?',choices:['Divide every coefficient by 2','Divide only 6 and 4 by 2','Leave 2 : 6 : 4 as it is'],answer:0,explanation:'Divide ALL coefficients by 2 to get 1 : 3 : 2. Dividing only some coefficients changes the ratio and may unbalance the equation.',wrong:['','You must divide every coefficient by the same number. Keeping the first 2 would leave too many nitrogen atoms on the left.','The atoms match, but all three coefficients share a factor of 2. Simplify the whole ratio.']}
];
const countQuestion={prompt:'How many oxygen atoms are represented by 3 Ca(OH)₂?',choices:['2 oxygen atoms','3 oxygen atoms','6 oxygen atoms'],answer:2,explanation:'The subscript 2 outside (OH) gives 2 O atoms per formula unit. The coefficient 3 multiplies that entire unit: 3 × 2 = 6 O atoms. The totals are 3 Ca, 6 O, and 6 H.',wrong:['That counts oxygen in one Ca(OH)₂ formula unit. The coefficient tells you there are three of those units.','The coefficient is 3, but each formula unit contains 2 O atoms. Multiply them together.','']};
function answerFeedback(question,choice){return{correct:choice===question.answer,text:choice===question.answer?question.explanation:question.wrong[choice]||'Choose one of the answers above.'};}
const chem=f=>f.replace(/\d+/g,n=>`<sub>${n}</sub>`);
let container,onPractice,lessonIndex=0,waterCount=2,guidedIndex=0;
const stages={},answers={};
const molecule=(atoms)=>`<span class="molecule" aria-hidden="true">${atoms.map(a=>`<span class="atom atom-${a}">${a}</span>`).join('')}</span>`;
const waterMolecules=n=>Array.from({length:n},()=>molecule(['H','O','H'])).join('');
function equation(r,values,previous=[]){
 let i=0;
 return `<div class="lesson-equation" aria-label="Chemical equation">${[r.left,r.right].map((side,j)=>`<div class="lesson-equation-side">${side.map((f,k)=>{const n=i++;return `${k?'<span class="lesson-symbol">+</span>':''}<span class="lesson-term ${previous.length&&values[n]!==previous[n]?'term-changed':''}"><b>${values[n]}</b> ${chem(f)}</span>`;}).join('')}</div>`).join('<span class="lesson-yields" aria-label="yields">→</span>')}</div>`;
}
function inventory(r,values,focus=[]){
 const result=root.Chemistry.check(r,values);
 return `<div class="lesson-inventory"><div class="section-heading"><h3>Count every element</h3><span class="small-label">${result.simplest?'BALANCED · SIMPLEST RATIO':result.balanced?'BALANCED · SIMPLIFY':'RECOUNT AFTER EACH CHANGE'}</span></div><table><caption class="sr-only">Atom totals at this step</caption><thead><tr><th scope="col">Element</th><th scope="col">Reactants</th><th scope="col">Products</th><th scope="col">Check</th></tr></thead><tbody>${result.atoms.map(a=>`<tr class="${focus.includes(a.element)?'count-focus':''}"><th scope="row">${a.element}</th><td>${a.left}</td><td>${a.right}</td><td class="${a.left===a.right?'matched':'unmatched'}">${a.left===a.right?'✓ Matched':'≠ Adjust'}</td></tr>`).join('')}</tbody></table></div>`;
}
function questionView(q,key){
 const selected=answers[key],result=selected===undefined?null:answerFeedback(q,selected);
 return `<section class="lesson-question"><p class="eyebrow">CHECK YOUR UNDERSTANDING</p><h3 id="guided-prompt" tabindex="-1">${q.prompt}</h3><div class="lesson-choices" role="group" aria-labelledby="guided-prompt">${q.choices.map((c,i)=>`<button type="button" data-answer="${i}" aria-pressed="${selected===i}">${c}${selected===i?(result.correct?' · ✓':' · Try again'):''}</button>`).join('')}</div><div id="lesson-feedback" class="lesson-feedback ${result?.correct?'is-correct':''}" role="status" tabindex="-1" ${result?'':'hidden'}>${result?result.text:''}</div></section>`;
}
function counting(){
 return `<section class="lesson-panel"><p class="eyebrow">THE SAME ATOMS · REARRANGED</p><h3>Atoms are conserved in a chemical reaction.</h3><p>The substances change as atoms form new combinations. The number of atoms of each element stays the same. Here, 4 H atoms and 2 O atoms appear on each side.</p><figure class="particle-reaction"><div><strong>2 H₂ + 1 O₂</strong><div class="molecule-tray">${molecule(['H','H'])}${molecule(['H','H'])}<span class="particle-plus" aria-hidden="true">+</span>${molecule(['O','O'])}</div><span>Reactants · 4 H, 2 O</span></div><span class="particle-arrow" aria-hidden="true">→</span><div><strong>2 H₂O</strong><div class="molecule-tray">${waterMolecules(2)}</div><span>Products · 4 H, 2 O</span></div><figcaption>H = hydrogen · O = oxygen. These groups illustrate atom counts, not molecular shapes.</figcaption></figure></section>
 <div class="lesson-two-column"><section class="lesson-panel"><p class="eyebrow">COEFFICIENT · THE NUMBER IN FRONT</p><h3>Change the amount.</h3><p>A coefficient multiplies <strong>every atom</strong> in the formula. A missing coefficient means 1.</p><div class="water-controls" role="group" aria-label="Number of water molecules">${[1,2,3].map(n=>`<button type="button" data-water="${n}" aria-pressed="${n===waterCount}">${n} H₂O</button>`).join('')}</div><div class="molecule-tray">${waterMolecules(waterCount)}</div><p class="atom-total" aria-live="polite">${waterCount} × 2 = <strong>${waterCount*2} H</strong> &nbsp; ${waterCount} × 1 = <strong>${waterCount} O</strong></p></section>
 <section class="lesson-panel"><p class="eyebrow">SUBSCRIPT · THE SMALL NUMBER BELOW</p><h3>Keep the substance the same.</h3><p>A subscript belongs to the chemical formula. Changing it changes the substance.</p><div class="formula-comparison"><div><strong>H<sub>2</sub>O</strong>${molecule(['H','O','H'])}<span>Water · 2 H, 1 O</span></div><div><strong>H<sub>2</sub>O<sub>2</sub></strong>${molecule(['H','O','O','H'])}<span>Hydrogen peroxide · 2 H, 2 O</span></div></div><p><strong>Balance with coefficients. Never edit subscripts to balance an equation.</strong></p></section></div>
 <section class="lesson-note"><h3>Parentheses multiply the entire group.</h3><p>Ca(OH)<sub>2</sub> contains <strong>1 Ca, 2 O, and 2 H</strong>. The 2 after the parentheses applies to both O and H, but not to Ca. A coefficient in front multiplies all three totals.</p></section>${questionView(countQuestion,'count')}`;
}
function worked(l){
 const index=stages[lessonIndex]||0,step=l.steps[index],previous=index?l.steps[index-1].values:[];
 return `<section class="worked-card"><div class="worked-heading"><p class="eyebrow">WORKED EXAMPLE · STEP ${index+1} OF ${l.steps.length}</p><span class="small-label">${index===l.steps.length-1?'FINAL CHECK':'FOLLOW EACH CHANGE'}</span></div>${equation(l,step.values,previous)}<p class="lesson-caption">${index?'Outlined terms show which coefficients changed.':'Coefficients of 1 are shown to make counting easier.'}</p><div class="worked-explanation"><span class="lesson-step-number">${index+1}</span><div><h3 id="worked-title" tabindex="-1">${step.title}</h3><p>${step.text}</p></div></div>${inventory(l,step.values,step.focus)}<div class="worked-controls"><button type="button" data-step="-1" ${index===0?'disabled':''}>← Previous step</button><span>${index+1} / ${l.steps.length}</span><button type="button" class="primary" data-step="1" ${index===l.steps.length-1?'disabled':''}>Next step →</button></div></section><section class="lesson-note"><h3>Take this with you</h3><p>${l.takeaway}</p></section>${lessonIndex===4?`<details class="lesson-panel lesson-details"><summary>What if oxygen needs a fraction?</summary><p>For ethane, balancing C and H gives C₂H₆ + O₂ → 2 CO₂ + 3 H₂O. The products contain 7 O atoms, so the temporary O₂ coefficient is 7/2.</p><p class="fraction-example">1 C₂H₆ + <strong>7/2</strong> O₂ → 2 CO₂ + 3 H₂O</p><p>Multiply <strong>every coefficient by 2</strong> to finish with whole numbers:</p><p class="fraction-example"><strong>2</strong> C₂H₆ + <strong>7</strong> O₂ → <strong>4</strong> CO₂ + <strong>6</strong> H₂O</p><p>Fractions can help during your reasoning. Practice accepts the final, smallest whole-number coefficients.</p></details>`:''}`;
}
function guidedView(l){
 if(guidedIndex===guided.length)return `<section class="worked-card"><p class="eyebrow">YOU HAVE THE PROCESS</p><h3 id="guided-prompt" tabindex="-1">Balanced, verified, and simplified.</h3>${equation(l,[1,3,2])}${inventory(l,[1,3,2])}<ol class="lesson-recap"><li>Read the formulas and count every element.</li><li>Change coefficients to match the totals.</li><li>Recount all elements after each change.</li><li>Reduce to the smallest whole-number ratio.</li></ol><p>In Practice, you choose all the coefficients. The atom inventory and hints are there when you need them.</p><div class="lesson-finish"><button type="button" class="primary" data-start-practice>Start practicing →</button><button type="button" data-restart-guided>Try this lesson again</button></div></section>`;
 const q=guided[guidedIndex],key='guided'+guidedIndex,correct=answers[key]===q.answer;
 return `<section class="worked-card"><p class="eyebrow">YOUR TURN · DECISION ${guidedIndex+1} OF ${guided.length}</p>${equation(l,q.values)}${guidedIndex===2?'<p>Suppose someone reports 2 : 6 : 4. The atoms match, but there is one more check.</p>':''}${inventory(l,q.values)}${questionView(q,key)}<button type="button" class="primary" data-guided-next ${correct?'':'disabled'}>${guidedIndex===2?'See the final check':'Continue'} →</button></section>`;
}
function render(focus){
 const l=lessons[lessonIndex];
 container.innerHTML=`<div class="learn-intro"><div><p class="eyebrow">LEARN · A GUIDED TUTORIAL</p><h2>Build a method. Then put it to work.</h2><p>Six short lessons, worked examples, and a guided finish. Explore at your own pace.</p></div><button type="button" data-start-practice>Go to Practice →</button></div><nav class="lesson-nav" aria-label="Tutorial lessons">${lessons.map((x,i)=>`<button type="button" data-lesson="${i}" aria-current="${i===lessonIndex?'step':'false'}"><span>${i+1}</span>${x.short}</button>`).join('')}</nav><article class="lesson-body"><div class="lesson-heading"><p class="eyebrow">LESSON ${lessonIndex+1} OF ${lessons.length}</p><h2 id="lesson-title" tabindex="-1">${l.title}</h2><p>${l.intro}</p></div>${l.kind==='count'?counting():l.kind==='worked'?worked(l):guidedView(l)}</article><nav class="lesson-footer" aria-label="Lesson navigation"><button type="button" data-lesson="${lessonIndex-1}" ${lessonIndex===0?'disabled':''}>← Previous lesson</button><span>${lessonIndex+1} of ${lessons.length}</span>${lessonIndex<lessons.length-1?`<button type="button" data-lesson="${lessonIndex+1}">Next lesson →</button>`:'<button type="button" class="primary" data-start-practice>Start practicing →</button>'}</nav>`;
 if(focus){const target=container.querySelector(focus);target?.focus({preventScroll:true});if(focus==='#lesson-title')container.querySelector('.lesson-nav').scrollIntoView({block:'start'});else if(focus==='#worked-title'||focus==='#guided-prompt')container.querySelector('.worked-card')?.scrollIntoView({block:'start'});else if(focus==='#lesson-feedback')target?.scrollIntoView({block:'nearest'});}
}
function mount(target,startPractice){
 container=target;onPractice=startPractice;render();
 container.addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b||b.disabled)return;
  if(b.hasAttribute('data-start-practice')){onPractice();return;}
  if(b.hasAttribute('data-lesson')){const n=Number(b.dataset.lesson);if(n>=0&&n<lessons.length){lessonIndex=n;render('#lesson-title');}return;}
  if(b.hasAttribute('data-water')){waterCount=Number(b.dataset.water);render(`[data-water="${waterCount}"]`);return;}
  if(b.hasAttribute('data-step')){const n=(stages[lessonIndex]||0)+Number(b.dataset.step);stages[lessonIndex]=Math.max(0,Math.min(lessons[lessonIndex].steps.length-1,n));render('#worked-title');return;}
  if(b.hasAttribute('data-answer')){answers[lessonIndex===0?'count':'guided'+guidedIndex]=Number(b.dataset.answer);render('#lesson-feedback');return;}
  if(b.hasAttribute('data-guided-next')&&answers['guided'+guidedIndex]===guided[guidedIndex].answer){guidedIndex++;render('#guided-prompt');return;}
  if(b.hasAttribute('data-restart-guided')){guidedIndex=0;guided.forEach((_,i)=>delete answers['guided'+i]);render('#guided-prompt');}
 });
}
function read(){const l=lessons[lessonIndex];return{lesson:lessonIndex+1,title:l.title,step:l.kind==='worked'?(stages[lessonIndex]||0)+1:l.kind==='guided'?Math.min(guidedIndex+1,guided.length):null};}
const api={mount,read,lessons,guided,countQuestion,answerFeedback};
if(typeof module!=='undefined')module.exports=api;else root.BalancingLessons=api;
})(typeof window==='undefined'?globalThis:window);
